remote_theme: rundocs/jekyll-rtd-theme
title: OpenBMP

lang: en
description: OpenBMP Documentation
source: "OpenBMP"
lang: en


readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-mentions
