#theme: jekyll-theme-midnight
remote_theme: pmarsceill/just-the-docs
title: OpenBMP
description: Documentation

site_author: Tim Evens
url: 'https://www.openbmp.org'
baseurl: 'https://github.com/openbmp'

color_scheme: "dark"
search_enabled: false

lsi: false
safe: true
source: 'https://github.com/openbnmp'
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

readme_index:
  with_frontmatter: true

