remote_theme: rundocs/jekyll-rtd-theme
title: OpenBMP

lang: en
description: OpenBMP Documentation
url: "https://www.openbmp.org"
baseurl: "https://github.com/OpenBMP"
lang: en


readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-mentions
